language: node_js
node_js:
  - "6"
  - "5"
  - "4"
sudo: false
services:
  - mongodb

before-script:
  - sleep 15

addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
